# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

global_vars:
  - name: firstname
    type: echo
    params:
      echo: "Krzysztof"
  - name: lastname
    type: echo
    params:
      echo: "Szpieg"
  # Paths variables
  - name: espanso_path
    type: echo
    params:
      echo: 'C:\Users\Admin\AppData\Roaming\espanso'


matches:
  ### Espanso matches
  # Path to Espanso config dir
  - trigger: ":espanso"
    replace: "{{espanso_path}}"

  # Path to Espanso config files
  - trigger: ":esp_cfg"
    replace: "config/{{config_file}}"
    vars:
      - name: config_file
        type: choice
        params:
          values:
            - "default.yml"

  # Path to Espanso match files
  - trigger: ":esp_match"
    replace: "match/{{match_file}}"
    vars:
      - name: match_file
        type: choice
        params:
          values:
            - "base.yml"
            
  ### Normal matches
  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Print signature in different languages
  - trigger: ":br"
    replace: "{{regards_type}},\n{{firstname}} {{lastname}}"
    vars:
      - name: regards_type
        type: choice
        params:
          values:
            - "Best regards"
            - "Pozdrawiam"
            - "Z wyrazami szacunku"