# My config

# Change the default prompt format
add_newline = true
command_timeout = 1000
format = """\
[╭╴](238)$os$username$hostname$time$directory\
$all[╰─](238)$character"""

[character]
success_symbol = '[ ](bold green)'
error_symbol = '[✗ ](bold red)'

# ---

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mint = ' '
NixOS = ' '
OpenBSD = '󰈺 '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = '󰍲 '

[time]
disabled = false
format = ' [$time]($style) '
time_format = '%R'

# ---

# Shows current directory
[directory]
style = 'bold green'
truncation_length = 1
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = 'bold red'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows the username
[username]
style_user = '#0089f5'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_symbol = ' '
ssh_only = false
format = 'on [$hostname](bold yellow) '
disabled = false

# Shows current git branch
[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold cyan'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold cyan'
conflicted = ' 🏳'
up_to_date = ' '
untracked = '  '
ahead = ' ⇡${count}'
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
behind = ' ⇣${count}'
stashed = ' 󰏗 '
modified = '  '
staged = ' [++\($count\)](cyan)'
renamed = ' 襁 '
deleted = '  '

# Other symbols/icons
[aws]
symbol = '  '
format = 'via [$symbol$version](bold #FF9900) '

[c]
symbol = ' '
format = 'via [$symbol$version](bold #659AD2) '

[dart]
symbol = ' '
format = 'via [$symbol$version](bold #0075BA) '

[docker_context]
symbol = ' '
format = 'via [$symbol$version](bold #1D63ED) '

[golang]
symbol = ' '
format = 'via [$symbol$version](bold #29BEB0) '

[java]
symbol = ' '
format = 'via [$symbol$version](bold #F8981D) '

[kubernetes]
symbol = '☸ '
format = 'via [$symbol$context\($namespace\)](bold #326DE6) '
disabled = false

[lua]
symbol = ' '
format = 'via [$symbol$version](bold white) '

[memory_usage]
symbol = '󰍛 '

[nodejs]
symbol = ' '
format = 'via [$symbol$version](bold #3C873A) '

[package]
symbol = '󰏗 '

[python]
symbol = ' '
format = 'via [$symbol$version](bold #FFD343) '

[ruby]
symbol = ' '
format = 'via [$symbol$version](bold #841B2D) '

[rust]
symbol = ' '
format = 'via [$symbol$version](bold #CE412B) '

[scala]
symbol = ' '
format = 'via [$symbol$version](bold #DE3423) '
