# My config

# Change the default prompt format
add_newline = true
command_timeout = 1000
format = """\
[╭╴](238)$os\
$all[╰─](238)$character"""

[character]
success_symbol = "[ ](bold green)"
error_symbol = "[✗ ](bold red)"

# ---

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

# ---

# Shows current directory
[directory]
style = 'bold green'
truncation_length = 1
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = 'bold red'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows the username
[username]
style_user = '#0089f5'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_symbol = " "
ssh_only = false
format = 'on [$hostname](bold yellow) '
disabled = false

# Shows current git branch
[git_branch]
symbol = " "
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold cyan'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold cyan'
conflicted = ' 🏳'
up_to_date = ' '
untracked = '  '
ahead = ' ⇡${count}'
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
behind = ' ⇣${count}'
stashed = ' 󰏗 '
modified = '  '
staged = ' [++\($count\)](cyan)'
renamed = ' 襁 '
deleted = '  '

# Other symbols/icons
[aws]
symbol = "  "
format = "[via $symbol$version] "

[c]
symbol = " "
format = "[via $symbol$version] "

[conda]
symbol = " "
format = "[via $symbol$version] "

[dart]
symbol = " "
format = "[via $symbol$version] "

[docker_context]
symbol = " "
format = "[via $symbol$version] "

[golang]
symbol = " "
format = "[via $symbol$version] "

[haskell]
symbol = " "
format = "[via $symbol$version] "

[java]
symbol = " "
format = "[$symbol$version] "

[kubernetes]
symbol = "☸ "
format = 'via [$symbol$context\($namespace\)](bold purple) '
disabled = false

[lua]
symbol = " "
format = "[via $symbol$version] "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "
format = "[via $symbol$version] "

[package]
symbol = "󰏗 "

[python]
symbol = " "
format = "[via $symbol$version]"

[ruby]
symbol = " "
format = "[via $symbol$version] "

[rust]
symbol = " "
format = "[via $symbol$version] "

[scala]
symbol = " "
format = "[via $symbol$version] "
