# My config

[os]
disabled = false
format = "$symbol "

[directory]
format = "[$path](underline #0089f5)[$read_only]($read_only_style) "
truncation_length = 3
home_symbol = "~"
read_only_style = "bold red"
read_only = " 󰌾"

[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[✗ ](bold red)"

[username]
format = "[$user](bold blue)[ @ ](red)"
disabled = false
show_always = true

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](green)" 
modified = "[${count}+](yellow)" 
deleted =  "[${count}-](red)" 
conflicted =  "[${count}~](red)" 
ahead = "⇡${count}"
behind = "⇣${count}"
untracked = "[${count}?](blue)" 
staged = "[${count}+](green)" 

[git_state]
style =	"bold red"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "rebase"
merge = "merge"	
revert = "revert"	
cherry_pick = "cherry"
bisect = "bisect"	
am = "am"	
am_or_rebase = "am/rebase"

# Nerd Font Symbols Preset
[aws]
symbol = "  "
format = "[$symbol$version] "

[buf]
symbol = " "
format = "[$symbol$version] "

[c]
symbol = " "
format = "[$symbol$version] "

[conda]
symbol = " "
format = "[$symbol$version] "

[dart]
symbol = " "
format = "[$symbol$version] "

[docker_context]
symbol = " "
format = "[$symbol$version] "

[elixir]
symbol = " "
format = "[$symbol$version] "

[elm]
symbol = " "
format = "[$symbol$version] "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "
format = "[$symbol$version] "

[guix_shell]
symbol = " "

[haskell]
symbol = " "
format = "[$symbol$version] "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = "[$symbol$version] "

[julia]
symbol = " "
format = "[$symbol$version] "

[lua]
symbol = " "
format = "[$symbol$version] "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = "[$symbol$version] "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[python]
symbol = " "
format = "[$symbol$version] "

[rlang]
symbol = "󰟔 "
format = "[$symbol$version] "

[ruby]
symbol = " "
format = "[$symbol$version] "

[rust]
symbol = " "
format = "[$symbol$version] "

[scala]
symbol = " "
format = "[$symbol$version] "

[spack]
symbol = "🅢 "
